# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20151024_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='page.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='preview',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='page_preview'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(help_text='The best video/photo size is 695x390', verbose_name='Text'),
        ),
    ]
