# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 20:01
from __future__ import unicode_literals

import apps.gallery.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20151024_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=sorl.thumbnail.fields.ImageField(height_field='height', upload_to=apps.gallery.models.get_path, width_field='width'),
        ),
    ]
